id: AA9DEEEC2
title: 'Beautiful Adornment of the Earth: In Praise of Kṣitigarbha'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:05:45.918178
  last_modified_at: 2022-03-01 04:05:45.918210
